### ISSUE TITLE
ETQ utilisateur, je peux consulter les suivis d'humeur mois par mois et renseigner (ou modifier) les dates passées

### ISSUE THREAD

**Issue by christophegrassi** [SocialGouv/1000jours#1099]
- étudier les modules existants de calendrier personnalisables (en reprenant les humeurs)

**Comment by alebret** [comment]
On peut utiliser un lib déjà présente dans l'appli : `react-native-calendars`

**Comment by christophegrassi** [comment]
Pour cette V1, nous partons sur :
![moodboard-v1](https://user-images.githubusercontent.com/64467998/160609351-e8e9974c-110c-4868-939c-6518b6cee010.png)
- l'affichage en mode "gros blocs" permet de renseigner l'humeur du jour
- et la modale permet de renseigner ou modifier les humeurs des jours passés...
