### ISSUE TITLE
ETQ utilisateur, je peux voir les articles affichés différemment

### ISSUE THREAD

**Issue by christophegrassi** [SocialGouv/1000jours#1123]
Selon la maquette définie dans Figma (et cf. image jointe) :
- [x] ordre des blocs
- [x] fermeture bloc « en bref »
- [x] bouton revenir en haut
- [x] article utile ? (sondage enregistré, stocké et marqueur pour stats) + mettre la phrase "Cet article vous a été utile ?"
- [ ] intégration du swipe (https://github.com/SocialGouv/1000jours/issues/1117)
- [ ] Accessibilité

**Comment by christophegrassi** [comment]
https://www.figma.com/file/CGIO51pUJH97Z65oP7xQiH/1000-jours?node-id=428%3A646

**Comment by alebret** [comment]
@christophegrassi du coup, on enlève bien la thématique (prendre soin de son enfant) et l'étape (de 0 à 3 mois) ?

**Comment by christophegrassi** [comment]
@alebret finalement, on laisse les labels "thématique" et "étape"

**Comment by christophegrassi** [comment]
@alebret, review PO :
- fonctionnement : parfait !
- design : il manque la petite ombre sur le bouton "revenir en haut" qui permettra une meilleure visibilité
- design : j'imagine que ce n'était pas possible d'avoir les deux boutons "oui" & "non" sur la même ligne que l'intitulé dans l'encart "article utile"

**Comment by alebret** [comment]
Pour les boutons oui/non sur la même ligne, ça risque de faire serré. 
Je peux tester en enlevant les icons, mais il faut garder une taille minimum pour l'accessibilité.

**Comment by christophegrassi** [comment]
> Pour les boutons oui/non sur la même ligne, ça risque de faire serré. Je peux tester en enlevant les icons, mais il faut garder une taille minimum pour l'accessibilité.

je laisserais comme ça... mais à valider avec @PerrineG

**Comment by alebret** [comment]
J'ai testé, et si l'écran est assez large, tout est affiché sur une seule ligne. Mais vu la longueur du texte, ça ne sera pas l'affichage le plus commun.
