### ISSUE TITLE
ETQ utilisateur, je vois un menu synthétisé (ou simplifié)

### ISSUE THREAD

**Issue by christophegrassi** [SocialGouv/1000jours#1133]
Rassemblement des items "Mentions légales", "Politiques de confidentialité" et "Accessibilité"
Eventuellement, système de hiérarchie et déploiement...

**Comment by PerrineG** [comment]
Proposition de maquette :
<img width="671" alt="menu" src="https://user-images.githubusercontent.com/59702865/160638135-e188f52e-9ebe-437c-a663-51d593e39f33.png">
