### ISSUE TITLE
ACCESSIBILITE v2 - Parenthèque

### ISSUE THREAD

**Issue by christophegrassi** [SocialGouv/1000jours#1179]
- état des lieux : déterminer le niveau d'accessibilité atteint à partir de notre fichier (https://docs.google.com/spreadsheets/d/13ENC9fDdmpIs-Yi_xPgf-PC46k-kG58P0uxtMmSbxP4/edit?pli=1#gid=0)
- action : appliquer les correctifs nécessaires

**Comment by alebret** [comment]
- [ ] (1.1) Supprimer le focus sur l'image pour chaque document
- [ ] Préciser le document télécharger sur le bouton "Télécharger"
- [ ] (11.3) Avoir des documents accessibles

**Comment by alebret** [comment]
@christophegrassi ci-dessus les points que j'ai relevé par rapport à l'état des lieux avec notre document. Le point 11.3 n'est pas de notre côté ...

**Comment by christophegrassi** [comment]
ok merci @alebret, nous étudierons plus tard comment rendre des documents accessibles ;)
