### ISSUE TITLE
ACCESSIBILITE v2 - Moodboard

### ISSUE THREAD

**Issue by christophegrassi** [SocialGouv/1000jours#1181]
- état des lieux : déterminer le niveau d'accessibilité atteint à partir de notre fichier (https://docs.google.com/spreadsheets/d/13ENC9fDdmpIs-Yi_xPgf-PC46k-kG58P0uxtMmSbxP4/edit?pli=1#gid=0)
- action : appliquer les correctifs nécessaires

**Comment by alebret** [comment]
- [ ] Remplacer le texte de la description
- [ ] (6.2) Modifier le carousel car la sélection de l'humeur est actuellement impossible.
- [ ] (8.2) Tester le zoom

Calendrier : 
- [ ] (5.1) bouton pour le mois suivant/précédent
- [ ] Les jours de la semaine tronqués 
Pour info, le focus sur une date cite : _Lundi 5 avril 2022 - button_
