### ISSUE TITLE
Changer le mail automatique “bénévole” –> “présidente”

### ISSUE THREAD

**Issue by maxime-lecoq** [SocialGouv/1000jours#1305]

**Comment by alebret** [comment]
Modification pour la confirmation de contact par mail et sms
- Mail : `Je suis Elise, la bénévole de Maman Blues` => `Je suis Elise, la présidente de l'association Maman Blues`
- Sms : `Je m'appelle Elise, je suis membre de l'association Maman Blues` =>`Je m'appelle Elise, je suis la présidente de l'association Maman Blues`
