### ISSUE TITLE
Bug - Affichage de plusieurs vidéos dans un article

### ISSUE THREAD

**Issue by alebret** [SocialGouv/1000jours#1310]
Lauren a créé un article avec plusieurs vidéos Youtube et seulement la première s'affiche correctement.
champs `texte_2`

A vérifier si dans le code on traite que la première vidéo ...
Fichier `textHtml.component.tsx` -> `fixVideoContent`

But : il faut pouvoir afficher plusieurs vidéo dans une seule article

**Comment by benguedj** [comment]
De base, on avait dit qu'il ne fallait pas intégrer directement les vidéos dans les articles car ça génère plusieurs bugs suivant la plateforme iOS / Android et suivant le lecteur vidéo. 

Le mieux c'est de faire un lien vers la vidéo avec une image (miniature de la vidéo).

**Comment by LaurenTron92** [comment]
Hello 
Voici l'article avec les modifications : https://backoffice-les1000jours.fabrique.social.gouv.fr/admin/plugins/content-manager/collectionType/application::article.article/176
