### ISSUE TITLE
Rajouter le libellé du département en base de donnée pour les infos démographiques

### ISSUE THREAD

**Issue by maxime-lecoq** [SocialGouv/1000jours#1480]
Quand je remplis le questionnaire et donne une adresse en outre mer alors le libellé de la région est conservé en BDD (exemple : 974 - La Réunion)

- [ ] Ajouter une colonne `departement_libelle` dans le BO
- [ ] Brancher le widget sur la nouvelle colonne

**Comment by alebret** [comment]
@maxime-lecoq On avait pas parlé d'une 2ième colonne avec le nom du département ? ou tu veux tout dans la même ?
