### ISSUE TITLE
Dashboard opération Elise

### ISSUE THREAD

**Issue by maxime-lecoq** [SocialGouv/1000jours#1574]
Donner accès un dashboard web à Elise pour renseigner les contacts pris / orientés 

Critères d'acceptance :

- [x] authentification via la table user de strapi
- [ ] pouvoir renseigner un nouveau contact : https://docs.google.com/spreadsheets/u/1/d/1Uh9tEtqt78LYd4qD9McVl-DyZtmdBG0bP6lKwLLPizQ/edit?usp=sharing
- [ ] pouvoir lister tous les contacts
- [ ] pouvoir modifier un élément de la liste

S'inspirer de : https://github.com/SocialGouv/tumeplay/tree/main/tumeplay-dashboard

**Comment by alebret** [comment]
Tâches : 
- [ ] Créer un nouveau repo `1000j-???`
- [ ] Intégrer l'authentification par Strapi + Création de user dans la collection `user`
- [ ] Page formulaire : création d'un nouveau contact
- [ ] Page formulaire : modification d'un contact
- [ ] Page : liste de tous les contacts
