### ISSUE TITLE
Bug - Tracker qui renvoit le mood du résultat

### ISSUE THREAD

**Issue by alebret** [SocialGouv/1000jours#1608]
Bug depuis la MEP du 19/01/2023 (v1.48.1)

Le tracker `Test - ParcoursA - Macaron Elise - bad-mood` n'est plus remonté 
(modèle `Test - ParcoursA/B/C/D - Macaron Elise - good-mood/moderate-mod/bad-mood`)
-> l'AB avait été supprimé dans la MEP du 19/01

**Comment by maxime-lecoq** [comment]
hello @MinaBarry je n'ai pas l'impression que ce soit bon ici.
quand je regarde les événements je vois que les premiers sont répétés. 
on retrouve deux fois les 3 trackers suivant : 
[Evènement] Démographie - Click - Home - Commencer
[Evènement] Home - Générique - Commencer
[Evènement] Home - Click - Commencer le test - 1000jblues-integration

Ensuite je vois les événements suivants : 
![image](https://user-images.githubusercontent.com/82037208/223169060-3f1c28db-678b-431c-af02-4d735a494512.png)
Problème : je n'ai pas cliqué sur recevoir les ressources par mail

En revanche j'ai bien de nouveau : Test - ParcoursB - Macaron Elise - bad-mood

Peux tu fixer les deux points précédents stp ?

**Comment by mbarry-ippon** [comment]
> hello @MinaBarry je n'ai pas l'impression que ce soit bon ici. quand je regarde les événements je vois que les premiers sont répétés. on retrouve deux fois les 3 trackers suivant : [Evènement] Démographie - Click - Home - Commencer [Evènement] Home - Générique - Commencer [Evènement] Home - Click - Commencer le test - 1000jblues-integration
> 
> Ensuite je vois les événements suivants : ![image](https://user-images.githubusercontent.com/82037208/223169060-3f1c28db-678b-431c-af02-4d735a494512.png) Problème : je n'ai pas cliqué sur recevoir les ressources par mail
> 
> En revanche j'ai bien de nouveau : Test - ParcoursB - Macaron Elise - bad-mood
> 
> Peux tu fixer les deux points précédents stp ?

l'AB testing des ressources sera enlever lors de la MEP de: 
https://github.com/SocialGouv/1000jours/issues/1622
https://github.com/SocialGouv/nos1000jours-blues-epds-widget/pull/134
