### ISSUE TITLE
Appli/Widget - Redirection vers le widget depuis l'app

### ISSUE THREAD

**Issue by alebret** [SocialGouv/1000jours#1611]
Pour remplacer l'intégration du widget directement dans l'app et éviter de nombreuse adaptations du widget, tester ce scénario.

Appli -> onglet Post Partum : 
- [x] Affichage de l'écran de présentation : https://miro.com/app/board/uXjVOzk_PoY=/?moveToWidget=3458764545846186376&cot=14
- [x] Ouverture du widget dans le navigateur avec la source : `1000j-application`

![image](https://user-images.githubusercontent.com/82037208/218497822-0bbb1e82-7c2c-49eb-ab6e-e21ffdc4fdde.png)

**Comment by maxime-lecoq** [comment]
Placer les partenaires :
- [ ] tous les publics en avant : caf, 1000 jours, monenfant.fr ...
- [ ] les petits privés et asso ensuite : petitenfance, mamanblues, oréhane, le salon du baby
- [ ] les gros privés derrières : mpedia, doctissimo, parents.fr, biba, bussy

Garder une marge sur l'écran entre les bords et les logos.

A la fin des logos, ajouter un 2e bouton OUVRIR LE QUESTIONNAIRE

**Comment by alebret** [comment]
@maxime-lecoq 
![Capture d’écran 2023-02-17 à 11 56 49](https://user-images.githubusercontent.com/20834756/219628642-4d88a5d1-d0e4-4446-bcf1-b1a3b5910680.png)
