### ISSUE TITLE
AB Testing - Rdv Elise

### ISSUE THREAD

**Issue by alebret** [SocialGouv/1000jours#1622]
Pouvoir prendre rdv avec Elise (ABCD test) + test d'attractivité

Maquettes : https://miro.com/app/board/uXjVOzk_PoY=/?moveToWidget=3458764546081055978&cot=14

- [ ] A : Ne rien changer
- [ ] B : Supprimer `Par sms` et `Par mail`, et les remplacer par `Choisissez votre créneaux` (ajout tracker)
- [ ] D : Ajouter  `Choisissez votre créneaux`  (ajout tracker)

**Comment by maxime-lecoq** [comment]
Comme convenu @mbarry-ippon j'ajoute qqs infos pour détailler cette story déjà complète d'Audrey.
Ecrite comme cela il n'y avait aucune confusion entre elle et moi, mais vu que c'est une grosse US et ta première j'ajoute qqs éléments : 

### Description
Pour qui ? L'équipe 1000J, les parents ayant un score >= 11 
Quoi ? Faire en sorte que les parents puissent prendre rendez-vous avec calendly dans le calendrier d'Elise
Pourquoi ? Afin de savoir si les parents pourraient plébisciter la prise de rdv VS SMS/email/chat

### Maquette
<img width="1193" alt="image" src="https://user-images.githubusercontent.com/82037208/220120160-cb2b7335-03cd-40b5-97e8-4c96a611bb11.png">

### Données
- https://calendly.com/rdv-nos1000jours/30min
- Parcours A : prise de contact par chat sms ou email
- Parcours B : prise de contact par chat ou par rendez-vous
- Parcours C : prise de contact par sms ou email ou par rendez-vous

### Critères d'acceptance
- [ ] les parcours A B et C sont en place
- [ ] chacun des modes de prise de rdv est traqué pour chaque parcours (eventcategory test)
- [ ] la prise de rdv est traquée aussi de manière générale (eventcategory contact) 
- [ ] un choix a été fait quant à l'intégration du calendly (inline, popout text, popout widget) en testant chaque intégration possible
- [ ] (si l'intégration possible nous le permet) traquer la confirmation de prise de rendez-vous au même titre que sms ou mail

**Comment by maxime-lecoq** [comment]
## Concernant les trackers : 

- [ ] Catégorie test :  
- Parcours A / sms / confirmation_envoi_sms
- Parcours A / email / confirmation_envoi_email
- Parcours A / chat / ouverture_chat
- Parcours B / rendez-vous / confirmation_envoi_rendez-vous
- Parcours B / chat / ouverture_chat
- Parcours C / sms / confirmation_envoi_sms
- Parcours C / email / confirmation_envoi_email
- Parcours C / rendez-vous / confirmation_envoi_rendez-vous

- [ ] Catégorie contact :  
- Choix du type de prise de contact / sms 
- Choix du type de prise de contact / Confirmation d'envoi de la demande de contact / sms
- Choix du type de prise de contact / email 
- Choix du type de prise de contact / Confirmation d'envoi de la demande de contact / email
- Choix du type de prise de contact / rendez-vous 
- Choix du type de prise de contact / Confirmation d'envoi de la demande de contact / rendez-vous

## Enregistrement en base de données (strapi)
- [ ] Contact et Demandes de contact : ajouter la prise de rendez-vous dans les possiblités

**Comment by maxime-lecoq** [comment]
Il manque l'enregistrement de la prise de rdv dans strapi au même titre que chat sms et email

![image](https://user-images.githubusercontent.com/82037208/223128814-3bdc7b3e-1b8f-4d1b-9e9c-005e9a8c98cb.png)

**Comment by maxime-lecoq** [comment]
le tracker sur la prise de rdv ne fonctionne pas : retourne null

![image](https://user-images.githubusercontent.com/82037208/223130915-caf17122-e81e-4a0b-a0cf-b94efc17dcdb.png)

**Comment by maxime-lecoq** [comment]
Je vois un cas où le parcours D est possible et que le résultat est le même que le parcours A. 
Comment sont attribués les parcours ? 
Si c'est à parts égales, il n'y aura pas de comparaison possibles dans le plébiscite d'une solution vs une autre. 
Cela poserait problème car il faudrait que chaque solution graphique soit visible autant de fois que les autres.

![image](https://user-images.githubusercontent.com/82037208/223134831-a0a2b200-e271-4bfc-b17d-63aa1287211f.png)

**Comment by maxime-lecoq** [comment]
J'ai fait un test sur Safari pour être sûr de pouvoir isoler mon scénario dans matomo : 
J'ai eu une intuition que je voulais vérifier. J'avais l'impression que sur mes tests, même si je n'appuyais que sur "rdv tel" tous les autres modes étaient aussi taggués. 
J'ai confirmé avec ce test, id visiteur : 0a83703caad83d9f
Dans ce test je n'ai effectué qu'une seule demande de contact, or je vois que le tag "Test - ParcoursB - confirmation_envoi_rendez-vous" est envoyé 3 fois et "Test - ParcoursB - ouverture_chat" est aussi loggué alors que je n'ai pas cliqué dessus

![image](https://user-images.githubusercontent.com/82037208/223141392-23b921e5-a53a-4c7c-b7b7-5062931da13f.png)

![image](https://user-images.githubusercontent.com/82037208/223140438-a2e81d2a-be20-438f-98d9-46e9c67e2001.png)

![image](https://user-images.githubusercontent.com/82037208/223142754-32d34a32-9b20-4945-aa00-0441905f31d5.png)

**Comment by maxime-lecoq** [comment]
Je viens de trouver un autre bug concernant les trackers : 
Au moment où je clique sur terminer le questionnaire EPDS, le tracker "afficher les ressources dispo" est envoyé. 
Il ne devrait pas être envoyé à ce moment là

![image](https://user-images.githubusercontent.com/82037208/223165740-f5fd6cb6-d784-4ca7-930b-0bf0bcaa8c77.png)

**Comment by maxime-lecoq** [comment]
Pour résumer, 5 bugs remontés pendant les tests : 

- [ ] enregistrement dans strapi non effectués (non évoqué pendant le grooming)
- [ ] tracker null renvoyé dans "choix de prise de contact"
- [ ] parcours D utilisé dans l'ABC test
- [ ] trackers en doublon
- [ ] tracker "afficher les ressources dispo" envoyé sans cliquer sur le bouton (déjà présent en prod)

**Comment by maxime-lecoq** [comment]
Notes : 
- tracker null renvoyé dans "choix de prise de contact" : je n'ai pas trouvé d'autres cas où null était renvoyé. A surveiller.
- parcours D utilisé dans l'ABC test : la variable contactTestABC peut prendre la valeur D, dans ce cas aucun mode de contact n'est proposé. Je ne l'ai pas vu passer à D d'elle même sans mon intervention pendant mes tests. En revanche la variable testABC est toujours présente : si on ne l'utilise plus on l'enlève !! autrement c'est les bugs assurés.
- trackers en doublon : ce n'est toujours pas bon (voir screenshot plus loin)

- Ce qu'on a en prod actuellement : 
![image](https://user-images.githubusercontent.com/82037208/223387068-cbf0fb6e-aeb1-47e7-b4dc-2af728443c86.png)

- En pre-prod : 
![image](https://user-images.githubusercontent.com/82037208/223387350-48fdfdc5-b0f1-4949-96dc-0482a5e19e50.png)
![image](https://user-images.githubusercontent.com/82037208/223387498-70ba30e4-e55f-4cc7-b77c-dc9af8d81b49.png)
![image](https://user-images.githubusercontent.com/82037208/223387544-f9eaddb6-38b2-4b6a-b135-fb8a3ac06512.png)
