### ISSUE TITLE
Widget: Implémenter la logique d'activation du chat côté front

### ISSUE THREAD

**Issue by mbarry-ippon** [SocialGouv/1000jours#1643]
Afficher ou non le chat en fonction de la variable récuperer depuis le back office.

- [x] Dépends de la mis en prod de: https://github.com/SocialGouv/1000jours/issues/1612

**Comment by maxime-lecoq** [comment]
Hello Mina,
Pour moi cette fonctionnalité ne fonctionne pas.

Je m'explique : 
- il est 10:32 un lundi
- je désactive le chat depuis le BO de preprod
- quand je passe le test je m'attends à ce que le mode "chat" ne soit pas proposé
- or il reste affiché comme proposition

Et après en relisant notre conversation sur mattermost je me demande s'il n'y a pas eu confusion. 
- "le chat pour le tester il faut que tu le test avant les horaires de "fermeture" sinon demain matin"

Quand on désactive le chat, ce mode ne peut être proposé.

**Comment by maxime-lecoq** [comment]
Vu avec Mina : 
* il y a un soucis en preprod
* besoin de relancer le BO ?
