### ISSUE TITLE
Témoignages et chiffres : enlever nos notes sur la première page

### ISSUE THREAD

**Issue by maxime-lecoq** [SocialGouv/1000jours#1660]
J'ai réussi à les enlever depuis le BO

**Comment by mbarry-ippon** [comment]
> J'ai réussi à les enlever depuis le BO

je les enleve du code ? pour éviter du code mort

**Comment by maxime-lecoq** [comment]
Test OK côté front. 
La collection est toujours dispo côté back. 
@MinaBarry : serait-il bon de l'enlever ? Si oui comment traquons nous cette tâche ?

**Comment by mbarry-ippon** [comment]
> Test OK côté front. La collection est toujours dispo côté back. @MinaBarry : serait-il bon de l'enlever ? Si oui comment traquons nous cette tâche ?

alors je sais pas si sur l'app il utilise aussi un caroussel de témoignage il faudrait que je vois avec benjamin, mais si c'est utilisé nul part oui il faudrait l'enlever pour eviter qu'on ai du code mort et des champs inutiles sur strapi.
