### ISSUE TITLE
Refonte de l'écran de résultat

### ISSUE THREAD

**Issue by mbarry-ippon** [SocialGouv/1000jours#1690]
- [ ] Enlever les intentions et donner son avis

- [ ] Ajout d'une barre de progression du score de la personne

- [ ] Ajout du texte explicatif du score pour emmener la personne à prendre contact

**Comment by maxime-lecoq** [comment]
Score 
- [ ] Décaler l’icône à gauche pour avoir ‘mon score au questionnaire’ sur la même 
- [ ] Préférer « Moyennement élevé (entre 9 et 11), élevé (entre 11 et 15), très élevé (au dessus de 15)

Témoignages 
Réduire l'espace entre le trait horizontal et le dernier témoignage
Changer les témoignages en fonction du score

Je ne suis pas seul.e
- [ ] Changer le texte pour :
"Chaque situation est différente et pourtant il existe une seule même maladie, la dépression post-partum. C'est une maladie qu'il est facile de guérir tant que l'on sait la détecter. Parler de ma situation m'aidera à m'en sortir.  
(saut de ligne)
Je veux être aidé.e dans ma démarche : "
- [ ] Rajouter le lien vers article DPP

Prendre contact
- [ ] Les 3 cartes ont les textes suivants 
Carte urgence : J'ai besoin d'aide en urgence. Je suis en situation de crise et j'ai besoin d'assistance immédiatement. 
Carte wanda : Je veux être accompagné.e. Je choisis un créneau qui me convient avec Wanda et ensemble nous trouvons une aide adaptée à ma situation.
Carte pros : Je prends rendez-vous avec un professionnel de santé. Spécialisés dans la dépression post-partum, ces professionnels peuvent m'aider.





Je demande de l'aide 

    * Enlever psychiatrique 
    * Enlever weekend
    * Mettre une carte (fond différent) pour les numéros d’urgence
    * Alerte : je suis en crise ? 
        * Afficher tout le temps si > 15
        * Autrement les weekend pour tout le monde (15 > X > 9)
    * Mode de contact : 
        * Garder entretient tel et SMS
* Trouver pro de santé
    * Enlever nom, et budget
    * Rajouter dans les cartes types de spécialistes
    * Rajouter un sous titre, « Ces professionnels sont reconnus pour leur appétence en santé périnatale et dépression post-partum » 
    * Plus d’infos : enlever
        * Préférer un bouton APPELER avec l’icône du téléphone
