### ISSUE TITLE
ETQ utilisateur, je peux voir le nouveau logo dans l'appli

### ISSUE THREAD

**Issue by christophegrassi** [SocialGouv/1000jours#178]

**Comment by christophegrassi** [comment]
Insertion du logo dans l'appli

**Comment by PerrineG** [comment]
Retour design : le logo n'a pas été changé sur la partie Onboarding et informations étapes.

![Onboarding 6 - slides](https://user-images.githubusercontent.com/59702865/116861265-1f9a0900-ac03-11eb-8235-ace0a278c879.jpg)
![Informations - j'attends un enfant 1](https://user-images.githubusercontent.com/59702865/116861268-2163cc80-ac03-11eb-9fc4-af6eafbdf0f6.jpg)

**Comment by Alezco** [comment]
Closed by #196
