### ISSUE TITLE
Bug : page blanche sur android quand on clique sur la flèche retour du navigateur (cf. video)

### ISSUE THREAD

**Issue by christophegrassi** [SocialGouv/1000jours#349]

**Comment by christophegrassi** [comment]
https://user-images.githubusercontent.com/64467998/122544862-80ec2f00-d02d-11eb-9c27-3a8c58b9107e.mp4

**Comment by Eric-Hei** [comment]
Sur IOS, même problème avec le swipe en arrière, par exemple en étant sur la page d'accueil
