### ISSUE TITLE
BUG - Expo Go - Erreur après avoir saisie la date de naissance pour un enfant né

### ISSUE THREAD

**Issue by maxime-lecoq** [SocialGouv/1000jours#494]

**Comment by maxime-lecoq** [comment]
![Screenshot_2021-07-07-14-49-18-260_host exp exponent](https://user-images.githubusercontent.com/82037208/124762321-1004ac80-df33-11eb-8639-ebfd904d8dbb.jpg)

![Screenshot_2021-07-07-14-50-36-783_host exp exponent](https://user-images.githubusercontent.com/82037208/124762333-12ff9d00-df33-11eb-9560-ec9dda4be48d.jpg)

**Comment by benguedj** [comment]
@maxime-lecoq Tu as toujours l'erreur ?

**Comment by maxime-lecoq** [comment]
J'essaie de tester sur Expo Go mais je suis bloqué au moment de valider la date de l'enfant. 
J'ai choisi "j'attends un enfant", la date du "09/07/2021" 
Je ne peux pas valider.
Le bouton est bleu mais quand je clique dessus je reste sur le même écran
@benguedj

**Comment by benguedj** [comment]
@maxime-lecoq  C'est bon, c'est dispo sur ExpoGo. Tu peux retester là.

**Comment by maxime-lecoq** [comment]
c'est bon pour moi @benguedj
