### ISSUE TITLE
ETQ utilisateur, je peux consulter la parenthèque = ensemble de documents, de médias,... à visualiser/télécharger

### ISSUE THREAD

**Issue by christophegrassi** [SocialGouv/1000jours#525]
en cours de définition ergonomie/design

**Comment by christophegrassi** [comment]
En fonction des maquettes définir par Perrine, définir les actions back et front (sous formes de tickets si possible).

La parenthèque sera accessible à partir du menu et l'étape 0 de la timeline...
Attention : nous activerons ces accès qu'une fois la bibliothèque constituée de premiers documents.

**Comment by christophegrassi** [comment]
Créer une autre branche spécifique à la parenthèque (ou système d'activation à prévoir)

**Comment by PerrineG** [comment]
Maquette affichage de la parenthèque sur la timeline : 

![Home - timeline parenthèque 2](https://user-images.githubusercontent.com/59702865/127007626-4db0c1f6-e931-4ae2-abe9-b6c99b1b4906.jpg)

**Comment by christophegrassi** [comment]
Pour précision, un document =
- un titre
- un fichier (pdf, jpg, png,...)
- une description
- une vignette (qui servira d'aperçu)
- lié à une ou plusieurs étape.s
- lié à une ou plusieurs thématique.s

**Comment by risseraka** [comment]
Il y a-t-il besoin d'un « type » ?
Est-ce qu'il y a besoin de plusieurs thématiques ?
S'il n'y en avait qu'une seule, ça pourrait servir de type (comme pour les événements).

**Comment by christophegrassi** [comment]
très bonne question...
je partirais sur une seule thématique... qui servirait donc de type.
Nous te confirmons asap
