### ISSUE TITLE
PRO EPDS - Pouvoir saisir ses coordonnées

### ISSUE THREAD

**Issue by alebret** [SocialGouv/1000jours#574]

**Comment by PerrineG** [comment]
Maquette accès espace pro - coordonnées :
![Écran_EspacePro_coordonées](https://user-images.githubusercontent.com/59702865/128015220-ef14e065-a10d-4c6c-a8c5-54046ac8324f.jpg)

**Comment by PerrineG** [comment]
Maquette accès à l'espace pro avec coordonnées :
![Écran_EspacePro_coordonées](https://user-images.githubusercontent.com/59702865/128015486-db114f67-03de-4143-bf48-233ab8ddc13c.jpg)

**Comment by alebret** [comment]
Pourquoi il y a écrit "L'appli" sur le logo ?

**Comment by PerrineG** [comment]
> Pourquoi il y a écrit "L'appli" sur le logo ?

C'est le "nouveau" logo pour différencier l'ensemble du projet 1000 premiers jours et l'application. Il a été créé par Santé Public France et nous devons utiliser celui là maintenant.

**Comment by maxime-lecoq** [comment]
Je m'attends à être redirigé sur l'application mobile, ou un moyen de la télécharger quand je clique sur le logo.
On va devoir le changer
