### ISSUE TITLE
ETQ utilisateur, je suis informé que les mails peuvent aller dans mes spams

### ISSUE THREAD

**Issue by PerrineG** [SocialGouv/1000jours#595]
Dans la modale "Être contacté(e)", ajouter une petite phrase en dessous du champ "Votre email*" qui précise que les retours peuvent être dans les spams : "Les retours peuvent se glisser dans vos spams ou mails indésirables, merci de les vérifier."
> Retour d'Élise.

**Comment by maxime-lecoq** [comment]
ok
