### ISSUE TITLE
ACCESSIBILITE - Ecran 7 : Calendrier

### ISSUE THREAD

**Issue by christophegrassi** [SocialGouv/1000jours#797]
### **Améliorations à effectuer sur IOS & Android :**
- [x] Les différentes puces correspondant à chaque date
Les différents pictogrammes du calendrier _(thème : Chaque élément graphique de décoration est-il ignoré par les technologies d’assistance ?)_
- [x] "Calendrier" doit être un titre, les dates doivent être des titres _(thème : a) Dans chaque écran, l’information est-elle structurée par l’utilisation appropriée de titres ? [PERTINENCE DES TEXTES DES TITRES PRESENTS])_
- [ ] Toutes les suites d'éléments devraient être des listes, notamment tous les éléments commençant par une puce _(thème : Dans chaque écran, chaque liste est-elle correctement structurée ?)_

### **Améliorations spécifiques à IOS :**
- [x] On ne peut pas atteindre la suite de la page _(thème : Chaque composant d’interface est-il contrôlable par le clavier et tout dispositif de pointage (hors cas particuliers) ?)_
- [x] A 200%, il n'est plus possible d'accéder au contenu de la page Calendrier _(thème : Dans chaque écran, l’utilisateur peut-il augmenter la taille des caractères de 200% au moins (hors cas particuliers) ?)_

### **Améliorations spécifiques à Android :**
aucune

**Comment by christophegrassi** [comment]
Retours Review PO :
- en mode VoiceOver, j'ai un encart vide sélectionné entre "Synchroniser" et le titre du premier événement... je pense que c'est l'élément "(Dernière synchro....)" qui est vide. Y a-t-il moyen de ne pas le rendre accessible par VoiceOver s'il est vide ?
Ok pour le reste

**Comment by benguedj** [comment]
@christophegrassi Ah oui bien vu, jvais regarder ça.
