### ISSUE TITLE
EPDS appli - changer le format des numéros de téléphone dans les mails envoyés par l'appli

### ISSUE THREAD

**Issue by maxime-lecoq** [SocialGouv/1000jours#930]
Pour qui ? Elise
Quoi ? Avoir un format de téléphone plus facile à lire
Pourquoi ? pour faciliter la prise de contact car actuellement tous les numéros se suivent et sont difficilement lisibles

<img width="729" alt="image" src="https://user-images.githubusercontent.com/82037208/146529303-4dc9eb3b-481e-45f2-97a8-7bb45bd52d52.png">

- [ ] séparer les numéros sans indicatif pays avec un espace tous les deux chiffres comme suit : 07 84 85 86 87
- [ ] séparer les numéros avec indicatif pays comme suit : +33 7 84 85 86 87

**Comment by alebret** [comment]
Côté Widget, la saisie permet uniquement 10 chiffres, donc on les formatages :
- [ ] 07 84 85 86 87
Côté appli, on a les formatages :
- [ ] 07 84 85 86 87
- [ ] +33 7 84 85 86 87
