### ISSUE TITLE
Enregistrer les résultats du test dans le BO

### ISSUE THREAD

**Issue by maxime-lecoq** [SocialGouv/1000jours#945]
Une fois que j'ai cliqué sur le bouton TERMINER, les résultats du test sont enregistrés dans le BO avec

- [x] la langue passée (ex: FR)
- [x] la clé de la source (ex: siteWebPro)
- [x] Un événement est envoyé à matomo pour chaque clic sur le bouton TERMINER

**Comment by alebret** [comment]
Ca veut dire que dans la réponse envoyée il n'y a pas le genre (inconnu par défaut donc)
